<nav class="navbar navbar-expand-lg menu">
		<div class="container">
			<div class="navbar-nav">
				<img src="/img/twitter_logo.png" class="menuIco" />
				<a class="menuItem" href="/timeline">

				<b>Home</b>
			</a>
			<a class="menuItem" href="/sair">
				<b>Sair</b>
			</a>
			<!-- <button onclick="myFunction()">Dark mode</button> -->
		</div>
		<button onclick="myFunction()" type="button" class="modo-dark btn btn-outline-primary"><b>Dark mode</b></button>
</nav>

	<div class="container mt-5">
		<div class="row pt-2">
			
			<div class="col-md-3">

				<div class="perfil">
					<div class="perfilTopo">

					</div>

					<div class="perfilPainel">
						
						<div class="row mt-2 mb-2">
							<div class="col mb-2">
								<span class="perfilPainelNome">
									<b><?= $this->view->info_usuario['nome'] ?> </b>
								</span>
							</div>
						</div>

						<div class="row mb-2">

							<div class="col">
								<span class="perfilPainelItem">Tweets</span><br />
								<span class="perfilPainelItemValor"></span>
								<?= $this->view->total_tweets['total_tweet'] ?>

							</div>

							<div class="col">
								<span class="perfilPainelItem">Seguindo</span><br />
								<span class="perfilPainelItemValor">
									<?= $this->view->total_seguindo['total_seguindo'] ?>
								</span>
								</div>

							<div class="col">
								<span class="perfilPainelItem">Seguidores</span><br />
								<span class="perfilPainelItemValor">
								<?= $this->view->total_seguidores['total_seguindo'] ?>
								</span>
							</div>

						</div>

					</div>
				</div>

			</div>

			<div class="col-md-6">
				<div class="row mb-2">
					<div class="col tweetBox">
						<form method="post" action="/tweet">
							<textarea class="form-control" name="tweet" id="exampleFormControlTextarea1" rows="3"></textarea>
							
							<div class="col mt-2 d-flex justify-content-end">
								<button type="submit" class="btn btn-primary">Tweet</button>
							</div>

						</form>
					</div>
				</div>
				<?php foreach($this->view->tweets as $id_tweet => $tweet) { ?>
				<div class="row tweet">
				
					<div class="col">
						<p><strong><?=$tweet['nome']?></strong><small><span class="text text-muted">- <?=$tweet['data']?></small></span></p>
						<p><?=$tweet['tweet']?></p>

						<br />
						<?php if($tweet['id_usuario'] == $_SESSION['id']) { ?>
						<form method="post" action="/remover_tweet? id=<?= $tweet['id']?>">
							<div class="col d-flex justify-content-end">
								<button type="submit"  class="btn btn-danger">
								<small>
									Remover
								</small></button>
							</div>
						</form>
						<?php } ?>
					</div>
				</div>
				<?php } ?>

			</div>


			<div class="col-md-3">
				<div class="quemSeguir">
					<span class="quemSeguirTitulo">Quem seguir</span><br />
					<hr />
					<a href="/quem_seguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
				</div>
				</div>

		</div>
	</div>
